name: macos-hep
channels:
  - conda-forge
  - defaults
  - pytorch-nightly
dependencies:
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - libcxx
  - matplotlib
  - pip
  - python=3.11.8
  - pytorch
  - torchvision
  - torchaudio
  - hepstats
  - hepunits
  - iminuit
  - seaborn
  - uproot
  - root
  - pyhf
  - shap
  - pip:
      - h5py
      - keras
      - libclang==18.1.1
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-io-gcs-filesystem
      - tensorflow-metal
      - pylorentz
      - scienceplots
      - mplhep
      - particle
      - boost-histogram
      -pydot